Upgraded to Vulkano 0.11. Added DejaVuSans font to repo
andrewhickman/vulkano-glyph pull request #2
Opened 2019-02-14 18:12 UTC by jsarasin

- Changed from vulkano-shaders-derive to vulkano-shaders.
- Updated shader definitions in the library and example
- Included the DejaVuSans.ttf as well as the license
- Bit of a hack to get the example to compile.

2019-02-14 19:14 UTC, andrewhickman commented
Thanks for the PR!

The vulkano version update looks good. I'd rather not add the font file though, just to avoid any issues with the license.

2019-02-14 19:31 UTC, andrewhickman requested changes

2019-02-14 19:31 UTC, andrewhickman commented on src/cache.rs
> +        });
Should propagate the error with
```suggestion
        })?;
```

2019-02-15 03:56 UTC, jsarasin commented
Changes made, font removed. Not sure if I need to do anything else on my end.

2019-02-15 08:13 UTC, andrewhickman commented
Thats great thanks, I will publish a new package this evening

2019-02-15 08:13 UTC, merged